#!/usr/bin/env python

import rospy
from geometry_msgs.msg import Twist
from turtlesim.srv import TeleportAbsolute
def move():
	rospy.init_node('robot_cleaner', anonymous=True)
	velocity_publisher = rospy.Publisher('/turtle1/cmd_vel', Twist, queue_size=10)
	teleport_publisher = rospy.Publisher('/turtle1/teleport_absolute', TeleportAbsolute, queue_size=10)

	tel_srv = TeleportAbsolute
	
	tel_srv = '[-5.0, 1.0, 0.0]'

	vel_msg = Twist()

	vel_msg.linear.x = 0
	vel_msg.linear.y = 0
	vel_msg.linear.z = 0
	vel_msg.angular.x = 0
	vel_msg.angular.y = 0
	vel_msg.angular.z = 0



	while not rospy.is_shutdown():
		t0 = rospy.Time.now().to_sec()
		t1 = t0

		while((t1-t0) < 1):
			velosity_publisher.publish(vel_msg)
			t1 = rospy.Time.now().to_sec()
		vel_msg.linear.x = 0
		velociry_publisher.publish(vel_msg)

if __name__ == '__main__':
	try:
		move()
	exept rospy.ROSInterruptExeption: pass	

	
